# -*- coding: utf-8 -*-
"""2024.09.02.hello-world.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pMLg8HSFfdCGMgyrjtoI-0ErK_fRnV6G
"""

print("hello world")

